language: elixir
elixir:
- 1.0.0
- 1.0.1
- 1.0.2
- 1.0.3
- 1.0.4
- 1.0.5
- 1.1.0
- 1.1.1
- 1.2.0
otp_release:
- 18.2
- 18.1
- 18.0
- 17.4
- 17.3
- 17.1
- 17.0
matrix:
  exclude:
  - elixir: 1.2.0
    otp_release: 17.0
  - elixir: 1.2.0
    otp_release: 17.1
  - elixir: 1.2.0
    otp_release: 17.3
  - elixir: 1.2.0
    otp_release: 17.4
  - elixir: 1.1.1
    otp_release: 18.2
  - elixir: 1.1.1
    otp_release: 18.1
  - elixir: 1.1.1
    otp_release: 18.0
  - elixir: 1.1.0
    otp_release: 18.2
  - elixir: 1.1.0
    otp_release: 18.1
  - elixir: 1.1.0
    otp_release: 18.0
  - elixir: 1.0.4
    otp_release: 18.2
  - elixir: 1.0.4
    otp_release: 18.1
  - elixir: 1.0.4
    otp_release: 18.0
  - elixir: 1.0.3
    otp_release: 18.2
  - elixir: 1.0.3
    otp_release: 18.1
  - elixir: 1.0.3
    otp_release: 18.0
  - elixir: 1.0.2
    otp_release: 18.2
  - elixir: 1.0.2
    otp_release: 18.1
  - elixir: 1.0.2
    otp_release: 18.0
  - elixir: 1.0.1
    otp_release: 18.2
  - elixir: 1.0.1
    otp_release: 18.1
  - elixir: 1.0.1
    otp_release: 18.0
  - elixir: 1.0.1
    otp_release: 17.0
  - elixir: 1.0.0
    otp_release: 18.2
  - elixir: 1.0.0
    otp_release: 18.1
  - elixir: 1.0.0
    otp_release: 18.0
  - elixir: 1.0.0
    otp_release: 17.0
before_script:
- git config --global user.email "builds@travis-ci.com"
- git config --global user.name "Travis CI"
- export GIT_TAG=otp-$TRAVIS_OTP_RELEASE-elixir-$TRAVIS_ELIXIR_VERSION
- git tag $GIT_TAG -a -f -m "Generated tag $GIT_TAG from TravisCI for build $TRAVIS_BUILD_NUMBER"
- mkdir -p plts
- mix local.hex --force
- mix deps.get
- mix do archive.build, archive.install --force
script:
- MIX_ENV=test mix dialyzer.plt
before_deploy:
- export RELEASE_PKG_FILE=$(ls plts/*.plt)
- echo "Deploying plt file $RELEASE_PKG_FILE to GitHub releases"
- git fetch --tags
- ls -R plts/*
deploy:
  provider: releases
  api_key:
    secure: Xrtv8ShQuoseJQ2bHeoIGL7Iqs2heCS7ddOwMnIheOuOa6gYyQAQiC0hh7hRiZShkPppv8z+eU5krg2+iLWsfpiSOh829v3ebcI+hK6fPrzsJRW9PLo5nKY+Byk0F0Sm6NzChncspC6GabdOEQCth7MuRazFJMW2yDYdGQM5f5FcPJcOReykDg2MnTl7Tp/DiUu6b7G6aEFleaY5CX9WgpjxRSPGfYPgeV585QuCmjkRrVf06c0Vnn5vg3+kMEPtjLp17gMHQrHCwai0pXNCRddKEunrpSlCUbiQbUZLzp8mYiy7ch+sy05urEwOb9Ixc5QlPhpps6fk/DJ9qV8geiJVIzvCKRiHVTOu3cFW0T8xK6Qm3ObTcFAjShlVtKWuck5wbYxy4sVPHzhg+QXNFvDMkQcFqouXRH9wW5LfKsFo3pwmFtu3HsiOUGnzbrH+9kNmgt6FKf1ACUpL38eXBI9ITrTvqr9Hg+5jPSzlAnAUayrLN5sBEBrHCbP1bJiCOeW7y+YBhcLKBo65ctGOD3v852BwUHq8IfxMneipr7bx7gaMQiWQJEd8WP3ELdluQtUDmUABlA0AO24x5Ge1hlmjzUeH5g9w8/+Su17LstgwsaohXzwbJv9whMlye/76sP+dzhlnUs2N4LAmVDqlo2gmQuaITl9ROFr04IrIrM8=
  file_glob: true
  file: "${RELEASE_PKG_FILE}"
  skip_cleanup: true
  all_branches: true
  on:
    repo: linearregression/travis_elixir_plt_generator
