language: elixir
elixir:
- 1.0.0
- 1.0.1
- 1.0.2
- 1.0.3
- 1.0.4
- 1.0.5
- 1.1.0
- 1.1.1
- 1.2.0
otp_release:
- 18.2
- 18.1
- 18.0
- 17.4
- 17.3
- 17.1
- 17.0
matrix:
  exclude:
  - elixir: 1.2.0
    otp_release: 17.0
  - elixir: 1.2.0
    otp_release: 17.1
  - elixir: 1.2.0
    otp_release: 17.3
  - elixir: 1.2.0
    otp_release: 17.4
  - elixir: 1.1.1
    otp_release: 18.2
  - elixir: 1.1.1
    otp_release: 18.1
  - elixir: 1.1.1
    otp_release: 18.0
  - elixir: 1.1.0
    otp_release: 18.2
  - elixir: 1.1.0
    otp_release: 18.1
  - elixir: 1.1.0
    otp_release: 18.0
  - elixir: 1.0.4
    otp_release: 18.2
  - elixir: 1.0.4
    otp_release: 18.1
  - elixir: 1.0.4
    otp_release: 18.0
  - elixir: 1.0.3
    otp_release: 18.2
  - elixir: 1.0.3
    otp_release: 18.1
  - elixir: 1.0.3
    otp_release: 18.0
  - elixir: 1.0.2
    otp_release: 18.2
  - elixir: 1.0.2
    otp_release: 18.1
  - elixir: 1.0.2
    otp_release: 18.0
  - elixir: 1.0.1
    otp_release: 18.2
  - elixir: 1.0.1
    otp_release: 18.1
  - elixir: 1.0.1
    otp_release: 18.0
  - elixir: 1.0.1
    otp_release: 17.0
  - elixir: 1.0.0
    otp_release: 18.2
  - elixir: 1.0.0
    otp_release: 18.1
  - elixir: 1.0.0
    otp_release: 18.0
  - elixir: 1.0.0
    otp_release: 17.0
env:
  global:
  - secure: Xrtv8ShQuoseJQ2bHeoIGL7Iqs2heCS7ddOwMnIheOuOa6gYyQAQiC0hh7hRiZShkPppv8z+eU5krg2+iLWsfpiSOh829v3ebcI+hK6fPrzsJRW9PLo5nKY+Byk0F0Sm6NzChncspC6GabdOEQCth7MuRazFJMW2yDYdGQM5f5FcPJcOReykDg2MnTl7Tp/DiUu6b7G6aEFleaY5CX9WgpjxRSPGfYPgeV585QuCmjkRrVf06c0Vnn5vg3+kMEPtjLp17gMHQrHCwai0pXNCRddKEunrpSlCUbiQbUZLzp8mYiy7ch+sy05urEwOb9Ixc5QlPhpps6fk/DJ9qV8geiJVIzvCKRiHVTOu3cFW0T8xK6Qm3ObTcFAjShlVtKWuck5wbYxy4sVPHzhg+QXNFvDMkQcFqouXRH9wW5LfKsFo3pwmFtu3HsiOUGnzbrH+9kNmgt6FKf1ACUpL38eXBI9ITrTvqr9Hg+5jPSzlAnAUayrLN5sBEBrHCbP1bJiCOeW7y+YBhcLKBo65ctGOD3v852BwUHq8IfxMneipr7bx7gaMQiWQJEd8WP3ELdluQtUDmUABlA0AO24x5Ge1hlmjzUeH5g9w8/+Su17LstgwsaohXzwbJv9whMlye/76sP+dzhlnUs2N4LAmVDqlo2gmQuaITl9ROFr04IrIrM8=
  - secure: p/d5B8sM9erdgQP0Qzu8SnjcrWrVnEFyS3l3qFRAvmygaubc3JqUFp5CvKueBhLzah02HGm648cyEvRGrkikjA4URsCJu0bQlQQoM+qEluGD4LqDHOSpgnALFDp40WjV+uMGYzolnfQdhDBLvJhIuYCebtEuWogCd7PpqUb0gaEoetX7g3eA9fx/9lz5xbqmwdy6VlALFLnovBUlbZBa9H7wEhrSj/08qrVOSNrAKrk1AfXQ1G3Ed6mJx0tgcR3N0DTMGeX7tVBHVd+wEQcjWYcnvXwBv7sFfOqB1aQ/MXBtwUk8pMXIkq05AP21E9IJiR4+C329Y0HUmDJwOVWHkQHXkC1hHqcW/xcACPYfnpv5JLwzX6OZ41/KzRurUl+3VjBS5NhLni2EUEsr9RPtDG7G6Igu9jB264lA8ZEq7TbYnLBl2qwqAPVgdnpwxhQszg8RSlj7i5gHn2MtwmRGsG0fdsdiKWaQlWnYB1BU+irDDLxT2k0QPVDve7nUN53r6XD4IJ4lo4sWtvHo0W1ueH3eddD6y3WoTcuo5jdN3vA5NYIW+qWercIPsU2VJZk1Ao8VMUPgG5k8B9NeeaRLS+tOFW7jLkNcR2o6GkQQwXJStvP886eaoglMKf5o3CPE6XOoXwvb6+qWoFUiwnpfx7SqvN+ps+8J/MjrL0v9gb4=
  - secure: tYK9YLj5MFR3czEHNjNuLrlZNViRQIz99mLUzHfaLw/zx1n30B1tj2agbdE5y/FDu0MjljmvYLRuXbj1St+zavHPuJGoWvRJwKht9+YsOaYJxpjhljmm7LsVi5jNvnwOKd1mS8h/u1UbcJtd2b9oRlCPBHC9iDpW0tSAqptyIv1pIT90/aP8SYYeaUGjUCDlUD5cH/cEwyDXEDlJ1Rpd0FuMY3C2d3sJdswyKdQjollzzuIdJ+378g15SYnTv2V/8eTsP7rA+9aO2hZb6ARBvAYkUkdPH/MgwhPP1DxStZwNUWxBalhSCSzydudYbrNcmdS/sW6REp8H42dXQjGwOtZCiU6A20Bdy3JdRmb44gNpJdIAQ7gN5fOraC7uVy+I/IBPLN/x+zDjHwLBUSa75jXCEK1A9cQoJoy8DBnpEVj0yNidFIC0Ncn09vhkmGrPqHkbxMwkWMFel6A0DjopEU33IuqZXwj/kHcPxE5ZX3hsRGMe/v9iIk4nI2JJbG818gXALIP2LRxjIVOF5jtlv2a673j7NaPAvlk6kT5WSceP0KR9REsPLwEpGUXx7J5vupTty+IB3QysKjyBYxhhrJa9GoDTIqAMwS2d/h4frp7eG+dBwmp8kcYMUasvhr7maBx2eZiRojMrFeYOLRYRmPxeuLh3TTMvRGVM0gEJMaE=
before_script:
- git config --global user.email ${GIT_EMAIL}
- git config --global user.name ${GIT_NAME}
- git remote rm origin
- git remote add origin ${GH_REF}
- mkdir -p plts
- mix local.hex --force
- mix deps.get
- mix do archive.build, archive.install --force
script:
- MIX_ENV=test mix dialyzer.plt
before_deploy:
- export RELEASE_PKG_FILE=$(ls plts/*.plt)
- echo "Deploying plt file $RELEASE_PKG_FILE to GitHub releases"
- export GIT_TAG=otp-$TRAVIS_OTP_RELEASE-elixir-$TRAVIS_ELIXIR_VERSION
- git checkout master
- git tag $GIT_TAG -a -f -m "Generated tag $GIT_TAG from TravisCI for build $TRAVIS_BUILD_NUMBER"
- git add -f ${RELEASE_PKG_FILE}
- git commit -m "Deploying ${RELEASE_PKG_FILE}"
- git push origin master --repo=${GH_POST_REF}
- git push --follow-tags --repo=${GH_POST_REF}
- git fetch --all
- ls -R plts/*
deploy:
  provider: releases
  file_glob: true
  file: ${RELEASE_PKG_FILE}
  skip_cleanup: true
  on:
    repo: linearregression/travis_elixir_plt_generator
    branch: master
