language: elixir
elixir:
- 1.0.0
- 1.0.1
- 1.0.2
- 1.0.3
- 1.0.4
- 1.0.5
- 1.1.0
- 1.1.1
- 1.2.0
otp_release:
- 18.2
- 18.1
- 18.0
- 17.4
- 17.3
- 17.1
- 17.0
before_script:
- git config --global user.email "builds@travis-ci.com"
- git config --global user.name "Travis CI"
- mkdir -p plts
- mix local.hex --force
- mix deps.get
- mix do archive.build, archive.install --force
script:
- MIX_ENV=test mix dialyzer.plt

before_deploy:
  - export RELEASE_PKG_FILE=$(ls plts/*.plt)
  - echo "Deploying plt file $RELEASE_PKG_FILE to GitHub releases"
  - export GIT_TAG=$TRAVIS_BRANCH-0.1.$TRAVIS_BUILD_NUMBER
  - git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
  - ls -R

deploy:
  provider: releases
  api_key:
    secure: VIQ0QZ7SH6p/Y0U5RwhtCEgT93MDx4yZASQmUGBVotfxb/5FkNYkZatxQ3+vo8SvjPcAFMWqj2Nf1IfNVcvtzyPPQFIX0GDs5Nm+f5M1brhxz0TaMKyORg/ONv8Xp6CxCMD0LQnRTAlgtvQSQWuuw9U06GFRxcc3zlP/F9NRB7tmvtSfwmGYs1cgwRo4/XVP1OTGZdMPZWxdgsCHvnYDE7PtI8orsOSfrNgSp/V7GcIN8u6/Wa7FKZiY1ekrDQ/wM7TT9ia+TBVAZoWk39rJ+Gx4Kb4CvZQ1hCWOlADJHp6BfIJL612S1gv/sT7/COLaQoA0kPAQzklRCF/PfNh4Mp5QadHsDLOGKPZNvLK2tlFcty95mk7t8UvjzPGWcwVtE6WWMOH9R0yB6/0HgnSllFJFv1hK8CTbRwotXZtSfKaFmLbvJ1snd5qjsoQPBJgTQoUWsFXCH2fgZUZLRraPw5pWjKNXRwX0ROWlcv5pTyrvCjqDLaGSr7hadzfGuC+LL1yjjtoFxDsLj85OewkRuTDDLNxsrVfoMwdZlnJfIfxsRD2UhWtbYJrRJk2U1or/QUXTZG1+vxeQLRXYqoLW+39GqYz1fp5g3Ckg/AVjGNNPp1wReJvrAOff/hv4hQjVZ+Xo3Wc5+aljHrASRLFaE8UP7cCCiVDq24BCafnJRUg=
  file: 
  -./plts/*.plt
  file_glob: true
  skip_cleanup: true
  on:
    repo: linearregression/travis_elixir_plt_generator
    tags: true
    
